# Generated by Django 4.2.8 on 2024-10-16 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0003_alter_athlete_estatura_alter_athlete_peso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Athlete',
        ),
        migrations.DeleteModel(
            name='Discipline',
        ),
    ]
