# Generated by Django 4.2.8 on 2024-10-24 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0005_discipline_athlete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='disciplinas',
        ),
        migrations.AddField(
            model_name='athlete',
            name='disciplinas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Athlete', to='users_auth.discipline'),
        ),
    ]
