# Generated by Django 4.2.8 on 2024-10-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0006_remove_athlete_disciplinas_athlete_disciplinas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='nombre',
        ),
        migrations.AddField(
            model_name='discipline',
            name='nombre_disciplina',
            field=models.CharField(default='Disciplina', max_length=100, verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripcion'),
        ),
        migrations.DeleteModel(
            name='Athlete',
        ),
    ]
