# Generated by Django 4.2.8 on 2024-10-30 15:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0007_remove_discipline_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='apellido',
            field=models.CharField(blank=True, max_length=120, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='estatura',
            field=models.FloatField(help_text='Estatura en Centimetros', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2024, 10, 30, 12, 14, 42, 888024)),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nombre',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nombre_disciplina',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customuser', to='users_auth.discipline'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='peso',
            field=models.FloatField(help_text='Peso en Kilogramos', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='nombre_disciplina',
            field=models.CharField(default='', max_length=100, verbose_name='Disciplina'),
        ),
    ]
