# Generated by Django 4.2.8 on 2024-10-30 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0008_customuser_apellido_customuser_estatura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2024, 10, 30, 15, 5, 53, 36970)),
        ),
    ]
